model:
  name: modern_cnn
  seed: 42
  freeze_backbone: false
  lr: 0.0001
  optimizer: adam
  weight_decay: 0.05
  device: 'cuda'
  num_workers: 10
  epochs: 200
  loss: cross_entropy
  output_dir: "./data/models/exp_modern_cnn"

resume: "./data/models/exp_modern_cnn/last_checkpoint.pth"
data_config: "./configs/data.yaml"